//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIMS.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class academictitle
    {
        public string code { get; set; }
        public string codeview { get; set; }
        public string name { get; set; }
        public string note { get; set; }
        public string edituser { get; set; }
        public Nullable<System.DateTime> edittime { get; set; }
        public Nullable<short> @lock { get; set; }
        public Nullable<System.DateTime> lockdate { get; set; }
        public Nullable<int> comparelevel { get; set; }
        public Nullable<int> theorder { get; set; }
        public string whois { get; set; }
        public Nullable<int> eduduty1 { get; set; }
        public Nullable<int> researchduty1 { get; set; }
        public Nullable<double> rate { get; set; }
        public Nullable<int> edureducerate { get; set; }
        public Nullable<int> researchreducerate { get; set; }
        public Nullable<int> eduduty { get; set; }
        public Nullable<int> researchduty { get; set; }
    }
}
