//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIMS.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class department
    {
        public string code { get; set; }
        public string codeview { get; set; }
        public string name { get; set; }
        public string note { get; set; }
        public string edituser { get; set; }
        public Nullable<System.DateTime> edittime { get; set; }
        public Nullable<short> @lock { get; set; }
        public Nullable<System.DateTime> lockdate { get; set; }
        public string parentcode { get; set; }
        public Nullable<int> comparelevel { get; set; }
        public Nullable<int> theorder { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string whois { get; set; }
        public Nullable<int> amount { get; set; }
        public string description { get; set; }
        public string universitycode { get; set; }
        public string originalcode { get; set; }
        public string extensioncode { get; set; }
        public Nullable<int> levelextension { get; set; }
        public string managelevelcode { get; set; }
        public string address { get; set; }
        public string regioncode { get; set; }
        public Nullable<System.DateTime> foundeddate { get; set; }
        public string foundeddateshow { get; set; }
        public string syscomponentcode { get; set; }
        public Nullable<int> partneronly { get; set; }
    }
}
