//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIMS.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class evidencenote
    {
        public string code { get; set; }
        public string evidencecode { get; set; }
        public string staffcode { get; set; }
        public string note { get; set; }
        public string edituser { get; set; }
        public Nullable<System.DateTime> edittime { get; set; }
        public Nullable<short> @lock { get; set; }
        public Nullable<System.DateTime> lockdate { get; set; }
        public string whois { get; set; }
        public string approvedstatuscode { get; set; }
        public Nullable<System.DateTime> notetime { get; set; }
        public string Thetype { get; set; }
        public string approvedstaff { get; set; }
        public Nullable<System.DateTime> approvedtime { get; set; }
        public string evidencestatuscode { get; set; }
        public string approvednote { get; set; }
    }
}
