//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIMS.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class evidence
    {
        public string code { get; set; }
        public string codeview { get; set; }
        public string name { get; set; }
        public string note { get; set; }
        public string edituser { get; set; }
        public Nullable<System.DateTime> edittime { get; set; }
        public Nullable<short> @lock { get; set; }
        public Nullable<System.DateTime> lockdate { get; set; }
        public string whois { get; set; }
        public string evidencetypecode { get; set; }
        public string storenote { get; set; }
        public string thetype { get; set; }
        public string provincecodoe { get; set; }
        public string districtcode { get; set; }
        public string towncode { get; set; }
        public string departmentcode { get; set; }
        public string enquirer { get; set; }
        public string enquirername { get; set; }
        public string enquirertitle { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string mailcode { get; set; }
        public string delivertypecode { get; set; }
        public Nullable<System.DateTime> enquiringthime { get; set; }
        public string staffcode { get; set; }
        public string evidencestatus { get; set; }
        public string approvedstatus { get; set; }
        public string reponsivestaff { get; set; }
        public string result { get; set; }
        public Nullable<System.DateTime> duetime { get; set; }
        public Nullable<System.DateTime> finishtime { get; set; }
        public Nullable<decimal> plustime { get; set; }
        public Nullable<System.DateTime> deliverytime { get; set; }
        public string deliverystaff { get; set; }
        public string deliverynote { get; set; }
    }
}
