//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIMS.MODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EIMSEntities : DbContext
    {
        public EIMSEntities()
            : base("name=EIMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<academiclevel> academiclevels { get; set; }
        public virtual DbSet<academictitle> academictitles { get; set; }
        public virtual DbSet<approvedstatu> approvedstatus { get; set; }
        public virtual DbSet<armyrank> armyranks { get; set; }
        public virtual DbSet<degree> degrees { get; set; }
        public virtual DbSet<deliverytype> deliverytypes { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<evidence> evidences { get; set; }
        public virtual DbSet<evidencematerial> evidencematerials { get; set; }
        public virtual DbSet<evidencenote> evidencenotes { get; set; }
        public virtual DbSet<evidencestaff> evidencestaffs { get; set; }
        public virtual DbSet<evidencestatu> evidencestatus { get; set; }
        public virtual DbSet<evidencetype> evidencetypes { get; set; }
        public virtual DbSet<inspectionmaterial> inspectionmaterials { get; set; }
        public virtual DbSet<leveltitle> leveltitles { get; set; }
        public virtual DbSet<managelevel> managelevels { get; set; }
        public virtual DbSet<material> materials { get; set; }
        public virtual DbSet<partyleveltitle> partyleveltitles { get; set; }
        public virtual DbSet<quantity> quantities { get; set; }
        public virtual DbSet<region> regions { get; set; }
        public virtual DbSet<staff> staffs { get; set; }
        public virtual DbSet<staffstatu> staffstatus { get; set; }
        public virtual DbSet<AppConfig> AppConfigs { get; set; }
    }
}
