//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIMS.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public string code { get; set; }
        public string codeview { get; set; }
        public string name { get; set; }
        public string note { get; set; }
        public string edituser { get; set; }
        public Nullable<System.DateTime> edittime { get; set; }
        public Nullable<short> @lock { get; set; }
        public Nullable<System.DateTime> lockdate { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string address { get; set; }
        public string academictitlecode { get; set; }
        public string degreecode { get; set; }
        public string leveltitlecode { get; set; }
        public string departmentcode { get; set; }
        public string armyrankcode { get; set; }
        public string partyleveltitlecode { get; set; }
        public string mobiphone { get; set; }
        public string tel { get; set; }
        public string userpassword { get; set; }
        public string photo { get; set; }
        public Nullable<int> manager { get; set; }
        public string email { get; set; }
        public Nullable<short> changepass { get; set; }
        public string academiclevelcode { get; set; }
        public string staffstatuscode { get; set; }
        public string provincecode { get; set; }
        public string districtcode { get; set; }
        public string towncode { get; set; }
        public string internalemail { get; set; }
        public string whois { get; set; }
        public Nullable<int> sex { get; set; }
        public string ethniccode { get; set; }
        public string religioncode { get; set; }
        public string hometown { get; set; }
        public string username { get; set; }
        public string universitycode { get; set; }
        public string civilid { get; set; }
        public string extensioncode { get; set; }
    }
}
